locations:
    pokeball_button: [540, 2000]
    pokémon_list_button: [240, 1840]
    eggs_tab: [870, 180]
    first_egg_distance_box: [80, 635, 285, 700]         # the whole thing: '0 / 10km'
    incubate_button_box: [430, 1360, 650, 1435]         # the text on INCUBATE button
    incubator_uses_left_box: [50, 1780, 230, 1850]      # the text of the leftmost incubator:
                                                        #   - it's the infinite symbol for the orange one
                                                        #   - it's the "X USES" for the paid ones

    im_a_passenger_button_box: [320, 1425, 760, 1490]   # the text on I'M A PASSENGER button
    eggs_label_box: [810, 340, 930, 400]                # the text EGGS on the tab
    oh_hatching_box: [430, 500, 700, 1000]               # the text Oh? when the egg hatches
                                                        #   (you'll have to wait until it
                                                        #   happens to get the coordinates)
    second_app_position: [800, 1050]                    # (optional) location to click after the app switcher is raised
    # MIUI9: second_app_position: [540, 900]                     # (optional) location to click after the app switcher is raised

    settings_button_box: [740, 180, 960, 240]                     # the text SETTINGS on the top right corner
    swipe_to_bottom: [120, 1900, 115, 500]
    pokemon_go_plus_menu_entry: [240, 1240]     # TODO: use box and check to avoisd clicking facebook
    nearby_pokemon_button: [930, 1130]
    goplus_button: [970, 450]

waits:
    pokeball_button: 2
    pokémon_list_button: 3
    eggs_tab: 3
    first_egg_distance_box: 3
    incubate_button_box: 3
    incubator_uses_left_box: 5
    second_app_position: 5
    swipe_to_bottom: 3
    pokemon_go_plus_button: 5
    settings_button: 3
    goplus_button: 7
    settings_button_box: 4


times:
    on_world: 250     # interval between eggs checks
    on_each_app: 120  # time to stay on each app if --switch is on
    refill_each: 580  # time between each items refill (for go+)
    refill_for: 240   # time to keep refilling (TOOD)
                      # TODO: remove this and OCR the number of items
    reconnect_goplus: 300  # time between each go++ reonnect
