locations:
    pokeball_button: [540, 2000]
    pokémon_list_button: [240, 1840]
    eggs_tab: [870, 180]
    first_egg_distance_box: [80, 635, 285, 700]         # the whole thing: '0 / 10km'
    incubate_button_box: [430, 1360, 650, 1435]         # the text on INCUBATE button
    incubator_uses_left_box: [50, 1780, 230, 1850]      # the text of the leftmost incubator:
                                                        #   - it's the infinite symbol for the orange one
                                                        #   - it's the "X USES" for the paid ones

    im_a_passenger_button_box: [320, 1425, 760, 1490]   # the text on I'M A PASSENGER button
    eggs_label_box: [810, 340, 930, 400]                # the text EGGS on the tab
    oh_hatching_box: [430, 500, 700, 1000]               # the text Oh? when the egg hatches
                                                        #   (you'll have to wait until it
                                                        #   happens to get the coordinates)
    second_app_position: [540, 900]                     # (optional) location to click after the app switcher is raised

waits:
    pokeball_button: 2
    pokémon_list_button: 3
    eggs_tab: 3
    first_egg_distance_box: 3
    incubate_button_box: 3
    incubator_uses_left_box: 5


times:
    on_world: 240     # interval between eggs checks
    on_each_app: 120  # time to stay on each app if --switch is on